drop table if exists books;

CREATE TABLE books
(
    ID INT(11) PRIMARY KEY NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR(200) NOT NULL,
    PUBLISHER VARCHAR(200) NOT NULL,
    STATUS INT(11) NOT NULL,
    RELEASE_DATE DATETIME,
    SUMMARY VARCHAR(2000) NOT NULL,
    VERSION INT(11) NOT NULL
);
